spring.application.name=api-gateway
server.port=8085
spring.security.oauth2.resourceserver.jwt.issuer-uri=${KEYCLOAK_ISSUER_URI:http://localhost:8080/realms/bank-realm}
gateway.client-service-url=${CLIENT_SERVICE_URL:http://localhost:8081}
gateway.account-service-url=${ACCOUNT_SERVICE_URL:http://localhost:8082}
gateway.ledger-service-url=${LEDGER_SERVICE_URL:http://localhost:8084}
gateway.payment-service-url=${PAYMENT_SERVICE_URL:http://localhost:8083}
internal.gateway.header-name=${INTERNAL_GATEWAY_HEADER_NAME:X-Internal-Gateway}
internal.gateway.secret=${INTERNAL_GATEWAY_SECRET:canbankx-gateway-secret}

management.endpoints.web.exposure.include=health,info,prometheus

springdoc.api-docs.enabled=true
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.urls[0].name=client-service
springdoc.swagger-ui.urls[0].url=/docs/client-service/v3/api-docs
springdoc.swagger-ui.urls[1].name=account-service
springdoc.swagger-ui.urls[1].url=/docs/account-service/v3/api-docs
