spring.application.name=client-service
server.port=8081

spring.datasource.url=jdbc:h2:mem:clientdb;MODE=PostgreSQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.jpa.show-sql=false

spring.security.oauth2.resourceserver.jwt.issuer-uri=${KEYCLOAK_ISSUER_URI:http://localhost:8080/realms/bank-realm}

keycloak.base-url=${KEYCLOAK_BASE_URL:http://localhost:8080}
keycloak.realm=${KEYCLOAK_REALM:bank-realm}
keycloak.admin-username=${KEYCLOAK_ADMIN_USERNAME:admin}
keycloak.admin-password=${KEYCLOAK_ADMIN_PASSWORD:admin}
keycloak.admin-client-id=${KEYCLOAK_ADMIN_CLIENT_ID:admin-cli}
keycloak.auth-client-id=${KEYCLOAK_AUTH_CLIENT_ID:bank-api}
internal.gateway.header-name=${INTERNAL_GATEWAY_HEADER_NAME:X-Internal-Gateway}
internal.gateway.secret=${INTERNAL_GATEWAY_SECRET:canbankx-gateway-secret}

management.endpoints.web.exposure.include=health,info,prometheus
